const canvas=document.querySelector('#field'),ctx=canvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let w=0,h=0,time=0,mode='sphere',paused=false,inView=true,cycleElapsed=0,pointer={x:0,y:0},rotation={x:0,y:0};
const count=1100,points=Array.from({length:count},(_,i)=>{const y=1-i/(count-1)*2,r=Math.sqrt(1-y*y),a=i*2.399963;return{x:Math.cos(a)*r,y,z:Math.sin(a)*r,u:(i%33)/32,v:Math.floor(i/33)/33}});
function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);w=box.width;h=box.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
new ResizeObserver(resize).observe(canvas);
new IntersectionObserver(entries=>{inView=entries[0].isIntersecting},{threshold:0}).observe(canvas);
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left-w/2)/w;pointer.y=(e.clientY-r.top-h/2)/h;if(paused&&!reduced)draw()});canvas.addEventListener('pointerleave',()=>pointer={x:0,y:0});
const modes=['sphere','wave','grid'];canvas.dataset.shape=mode;
function toggleMotion(){if(reduced)return;paused=!paused;canvas.setAttribute('aria-pressed',String(paused));canvas.setAttribute('aria-label',paused?'粒子实验已暂停，点击或按空格继续':'自动切换的粒子实验，点击或按空格暂停')}
canvas.addEventListener('click',toggleMotion);canvas.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();toggleMotion()}});
function project(x,y,z){const angle=time*.12+rotation.x*.8,tilt=.25+rotation.y*.55;const rx=x*Math.cos(angle)+z*Math.sin(angle),rz=-x*Math.sin(angle)+z*Math.cos(angle),ry=y*Math.cos(tilt)-rz*Math.sin(tilt),depth=y*Math.sin(tilt)+rz*Math.cos(tilt),size=Math.min(w*.41,h*.39),scale=3.5/(3.5-depth*.25);return{x:w*.53+rx*size*scale,y:h*.46+ry*size*scale,z:depth}}
function draw(){if(!w||!h)return;ctx.clearRect(0,0,w,h);if(!reduced){rotation.x+=(pointer.x-rotation.x)*.07;rotation.y+=(pointer.y-rotation.y)*.07}
 const size=Math.min(w*.41,h*.39),cx=w*.53,cy=h*.46;
 const halo=ctx.createRadialGradient(cx,cy,size*.1,cx,cy,size*1.5);halo.addColorStop(0,'#c3ed6214');halo.addColorStop(.6,'#c3ed6207');halo.addColorStop(1,'#c3ed6200');ctx.fillStyle=halo;ctx.fillRect(0,0,w,h);
 // Fine orbital paths give the field a readable three-dimensional structure.
 ctx.lineWidth=.65;for(let ring=0;ring<7;ring++){ctx.beginPath();for(let i=0;i<=90;i++){const a=i/90*Math.PI*2,b=ring/7*Math.PI;const x=Math.cos(a),y=Math.sin(a)*Math.cos(b),z=Math.sin(a)*Math.sin(b),p=project(x*1.08,y*1.08,z*1.08);if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.strokeStyle=mode==='sphere'?'#c3ed622a':'#c3ed6210';ctx.stroke()}
 const dots=points.map(p=>{let {x,y,z}=p;if(mode==='wave'){x=(p.u-.5)*2.7;z=(p.v-.5)*2.5;y=Math.sin(x*2+time)*.35+Math.cos(z*3+time)*.22}else if(mode==='grid'){x=(p.u-.5)*2.5;z=(p.v-.5)*2.5;y=.1*Math.sin(time+x*4+z*4)}if(p.cx===undefined){p.cx=p.x;p.cy=p.y;p.cz=p.z}const mix=reduced||paused?1:.075;p.cx+=(x-p.cx)*mix;p.cy+=(y-p.cy)*mix;p.cz+=(z-p.cz)*mix;return project(p.cx,p.cy,p.cz)}).sort((a,b)=>a.z-b.z);
 dots.forEach(p=>{ctx.fillStyle=`rgba(195,237,98,${.15+(p.z+1.5)/3*.72})`;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.5,1.25+p.z*.62),0,Math.PI*2);ctx.fill()});
 // A single orbiting beacon is the primary ambient movement.
 const a=time*.48,p=project(Math.cos(a)*1.08,Math.sin(a)*.65,Math.sin(a)*.86);ctx.shadowColor='#c3ed62';ctx.shadowBlur=18;ctx.fillStyle='#e7ffc0';ctx.beginPath();ctx.arc(p.x,p.y,3.3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
}
let prev=0,lastFrame=0;function animate(t){const elapsed=lastFrame?Math.min(t-lastFrame,100):0;lastFrame=t;if(!paused&&!document.hidden&&inView){cycleElapsed+=elapsed;if(cycleElapsed>=3000){cycleElapsed%=3000;mode=modes[(modes.indexOf(mode)+1)%modes.length];canvas.dataset.shape=mode}if(t-prev>32){time+=.026;draw();prev=t}}if(!reduced)requestAnimationFrame(animate)}resize();if(!reduced)requestAnimationFrame(animate);
document.querySelectorAll('.magnet').forEach(el=>{el.addEventListener('pointermove',e=>{if(reduced||e.pointerType==='touch')return;const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
if(!reduced&&matchMedia('(hover:hover) and (pointer:fine)').matches)document.querySelectorAll('.project-row .project-image').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;el.style.setProperty('--tilt-x',`${(y-.5)*-5}deg`);el.style.setProperty('--tilt-y',`${(x-.5)*6}deg`);el.style.setProperty('--light-x',`${x*100}%`);el.style.setProperty('--light-y',`${y*100}%`)});el.addEventListener('pointerleave',()=>{el.style.setProperty('--tilt-x','0deg');el.style.setProperty('--tilt-y','0deg')})});
const method=[['?','先问，哪里值得做。','把目标拆到真实用户动作。求职知识库先解决信息比较，销售工作台先解决决策与执行边界，避免从模型能力倒推需求。','速聘 / AAS 工作台'],['↗','用体验检验抽象方案。','尽早跑通关键路径。照片项目先完成照片墙、进入场景与漫游；内容平台从一句主题串到可查看的封面结果。','Photo to 3D / 千川内容平台'],['{}','把边界写进执行过程。','区分模型、确定性代码和人工的职责。建立数据来源、状态转换、合规闸门和重试上限，让失败有可解释的处理路径。','AAS 工作台 / 千川内容平台'],['↻','让失败推动下一次迭代。','保留 Trace、重放路径和修改约束，按知识、检索、生成与流程定位问题；把修复结果重新带回验证，而非仅修改一段 Prompt。','AAS 工作台 / 各项目 README']];const tabs=[...document.querySelectorAll('[data-step]')];function setStep(i){tabs.forEach((b,n)=>{b.setAttribute('aria-selected',n===i);b.tabIndex=n===i?0:-1});const panel=document.querySelector('#method-panel');if(!reduced)panel.animate([{opacity:.3,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'cubic-bezier(.22,1,.36,1)'});panel.setAttribute('aria-labelledby','step-'+i);document.querySelector('.method-symbol').textContent=method[i][0];document.querySelector('#method-title').textContent=method[i][1];document.querySelector('#method-description').textContent=method[i][2];document.querySelector('#method-evidence').textContent='对应作品：'+method[i][3]}tabs.forEach((b,i)=>{b.onclick=()=>setStep(i);b.onkeydown=e=>{let n=i;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i+3)%4;else return;e.preventDefault();setStep(n);tabs[n].focus()}});document.querySelector('#copy-email').onclick=async()=>{try{await navigator.clipboard.writeText('291623933@qq.com');document.querySelector('#copy-status').textContent='已复制：291623933@qq.com'}catch{document.querySelector('#copy-status').textContent='邮箱：291623933@qq.com'}};
if(!reduced){document.documentElement.classList.add('motion');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))}

if(reduced){canvas.removeAttribute('role');canvas.removeAttribute('tabindex');canvas.removeAttribute('aria-pressed');canvas.setAttribute('aria-label','静态空间粒子图，系统已减弱动态效果')}

// Media plays only while visible; user pauses survive scrolling and tab changes.
const mediaStates=new Map();
function syncVideo(video){const state=mediaStates.get(video);if(state.visible&&!document.hidden&&!state.userPaused){if(!video.src)video.src=video.dataset.src;video.play().catch(()=>{});}else video.pause()}
const mediaObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{mediaStates.get(entry.target).visible=entry.isIntersecting;syncVideo(entry.target)}),{threshold:.2});
document.querySelectorAll('.project-video').forEach(card=>{const video=card.querySelector('video'),button=card.querySelector('.video-toggle');video.muted=true;mediaStates.set(video,{visible:false,userPaused:reduced});mediaObserver.observe(video);const update=()=>{button.textContent=video.paused?'播放':'暂停';button.setAttribute('aria-pressed',String(!video.paused));button.setAttribute('aria-label',(video.paused?'播放':'暂停')+video.getAttribute('aria-label'))};video.addEventListener('play',update);video.addEventListener('pause',update);button.addEventListener('click',()=>{const state=mediaStates.get(video);state.userPaused=!video.paused;syncVideo(video);update()});const sound=card.querySelector('.video-sound');if(sound)sound.addEventListener('click',()=>{video.muted=!video.muted;sound.textContent=video.muted?'声音关闭':'声音开启';sound.setAttribute('aria-pressed',String(!video.muted));sound.setAttribute('aria-label',(video.muted?'开启':'关闭')+video.getAttribute('aria-label')+'声音')})});
document.addEventListener('visibilitychange',()=>mediaStates.forEach((_,video)=>syncVideo(video)));

const catalog=[...document.querySelectorAll('.work[data-group],.featured[data-group]')];document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const value=button.dataset.filter;let count=0;catalog.forEach(item=>{const show=value==='全部'||item.dataset.group===value;item.hidden=!show;if(show){count++;item.classList.add('visible')}});document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#filter-status').textContent='展示 '+count+' 件作品';}));
